# Generated by Django 5.1.2 on 2024-10-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_film_category_alter_film_release_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
